# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MapChat

  target 'MapChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MapChatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Alamofire'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'PopupDialog'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'lottie-ios'
  pod 'SwiftyJSON'
  pod 'Cards'
  pod 'VSTwitterTextCounter'
end
